{
 "title": "Containers without limits",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Containers without memory limits by namespace",
   "type": "timeseries",
   "description": "Except kube-system ns",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (namespace)(count by (namespace,pod,container)(kube_pod_container_info{container!=\"\",namespace!=\"kube-system\"}) unless sum by (namespace,pod,container)(kube_pod_container_resource_limits{resource=\"memory\"}))"
    }
   ]
  },
  {
   "title": "Containers without CPU limits by namespace",
   "type": "timeseries",
   "description": "Except \"kube-system\" namespace",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (namespace)(count by (namespace,pod,container)(kube_pod_container_info{container!=\"\",namespace!=\"kube-system\"}) unless sum by (namespace,pod,container)(kube_pod_container_resource_limits{resource=\"cpu\"}))"
    }
   ]
  },
  {
   "title": "Top 10 containers without memory limits, using more memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "topk(10,sum by (namespace,pod,container)(container_memory_usage_bytes{container!=\"\"}) unless sum by (namespace,pod,container)(kube_pod_container_resource_limits{resource=\"memory\"}))"
    }
   ]
  },
  {
   "title": "Top 10 containers without CPU limits, using more CPU",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "topk(10,sum by (namespace,pod,container)(rate(container_cpu_usage_seconds_total{container!=\"\"}[5m])) unless sum by (namespace,pod,container)(kube_pod_container_resource_limits{resource=\"cpu\"}))"
    }
   ]
  }
 ]
}