{
 "title": "Monitor resource wasted",
 "time": { "from": "now-2m", "to": "now" },
 "panels": [
  {
   "title": "Detecting unused CPU Cores",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum((rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\",service=\"prometheus-release-kube-pr-kubelet\"}[$__rate_interval]) - on (namespace,pod,container) group_left avg by (namespace,pod,container)(kube_pod_container_resource_requests{resource=\"cpu\"})) * -1 >0)"
    }
   ]
  },
  {
   "title": "Detecting unused memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(\r\n  (\r\n    container_memory_usage_bytes{container!=\"POD\",container!=\"\",service=\"prometheus-release-kube-pr-kubelet\"}\r\n    - on (namespace,pod,container) group_left(avg) kube_pod_container_resource_requests{resource=\"memory\"}\r\n  ) * -1 > 0\r\n) / (1024*1024*1024)\r\n"
    }
   ]
  },
  {
   "title": "Namespaces are wasting more CPU cores",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (namespace)((rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\",service=\"prometheus-release-kube-pr-kubelet\"}[$__rate_interval]) - on (namespace,pod,container) group_left avg by (namespace,pod,container)(kube_pod_container_resource_requests{resource=\"cpu\"})) * -1 >0)"
    }
   ]
  },
  {
   "title": "Detect namespaces are wasting more memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (namespace)(\r\n  (\r\n    container_memory_usage_bytes{container!=\"POD\", container!=\"\",service=\"prometheus-release-kube-pr-kubelet\",namespace=\"demo3\"}\r\n    - on(namespace, pod, container) group_left(avg) kube_pod_container_resource_requests{resource=\"memory\"}\r\n  ) * -1 > 0\r\n) / (1024*1024*1024)"
    }
   ]
  },
  {
   "title": "Top 10 CPU-wasted containers",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "topk(10,sum by (namespace,pod,container)((rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\",service=\"prometheus-release-kube-pr-kubelet\"}[$__rate_interval]) - on (namespace,pod,container) group_left avg by (namespace,pod,container)(kube_pod_container_resource_requests{resource=\"cpu\"})) * -1 >0))"
    }
   ]
  },
  {
   "title": "Top 10 Memory-wasted containers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "topk(10,\r\n  ((\r\n    container_memory_usage_bytes{container!=\"POD\", container!=\"\",service=\"prometheus-release-kube-pr-kubelet\"}\r\n    - on(namespace, pod, container) group_left kube_pod_container_resource_requests{resource=\"memory\"}\r\n  ) * -1 >0) / (1024*1024*1024)  # Convert to megabytes for easier interpretation\r\n)"
    }
   ]
  }
 ]
}